commands:
  # Horas
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Me diga as horas.
    entity: time
    action: getTime
  
  # Data
  - command:
    input: Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input: Data de hoje.
    entity: time
    action: getDate

  # Tempo
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWeather
  - command:
    input: Como está o clima?
    entity: weather
    action: getWeather

  # O que a Bosch faz
  - command:
    input: O que a bosch faz
    entity: bosch
    action: 11
  - command:
    input: Em quais ramos a Bosch atua
    entity: bosch
    action: 11

  # Quem é o presidente/CEO da bosch
  - command:
    input: Quem é o presidente da bosch
    entity: bosch
    action: 2
  - command:
    input: Quem é o CEO da bosch
    entity: bosch
    action: 2
  